// Package drpc runs the gRPC programming model over unreliable datagram
// channels — UDP, WebRTC data channels — and over reliable ones, without
// HTTP/2.
//
// Conn implements [google.golang.org/grpc.ClientConnInterface] and Server
// implements [google.golang.org/grpc.ServiceRegistrar], so code generated by
// protoc-gen-go-grpc plugs in unchanged:
//
//	pc, _ := net.ListenUDP("udp", laddr)
//	gw := udp.NewGateway(pc)                  // transport/udp
//	srv := drpc.NewServer(gw)
//	pb.RegisterSensorServiceServer(srv, &handler{})
//	go gw.Serve(ctx, srv)
//
//	c, _ := net.Dial("udp", addr)
//	conn := drpc.NewConn(udp.New(c))          // the transport attaches itself
//	defer conn.Close(nil)                     // one Close tears everything down
//	client := pb.NewSensorServiceClient(conn)
//
// # Two modes, derived from the channel
//
// A transport reports whether it loses, duplicates or reorders messages
// (TransportInfo); a gateway serving channels of differing reliability
// annotates each one per peer (NewReliableContext). The core then runs:
//
//   - Unreliable mode — the sensor path. Streams deliver an ordered
//     subsequence of what was sent: never reordered, never duplicated, gaps
//     allowed. Lost control frames are recovered by bounded retransmission,
//     tombstones, probes and peer liveness, so no call ever hangs: every
//     termination path has a stated bound.
//   - Reliable mode — gRPC-over-WebSocket / reliable-DataChannel semantics.
//     Timers and retransmission are off, delivery is the exact sequence, any
//     gap or duplicate fails the call with INTERNAL, and per-stream flow
//     control keeps one slow consumer from stalling the other calls sharing
//     the channel.
//
// # gRPC surface
//
// All four RPC types, header and trailer metadata (binary "-bin" keys
// included), status codes and details, interceptors, codecs and compressors,
// deadlines propagated and enforced on both ends, per-call size limits,
// PerRPCCredentials, peer addressing, GetServiceInfo (so reflection works),
// and a stats.Handler surface. What is deliberately absent — WaitForReady,
// transparent retry, name resolution and load balancing — needs a
// connectivity model this transport does not have.
//
// # Observability
//
// WithStatsHandler takes a [google.golang.org/grpc/stats.Handler]; and
// WithProtocolStats takes an observer for the datagram-specific events gRPC
// has no concept of — skipped messages (the per-stream gap counter), rx
// drops, RESETs, retransmissions, probes, liveness expiry, tombstone replays
// and flow-control stalls. Counters is a ready-made sink for them.
//
// # Where the rules live
//
// PROTOCOL.md in the repository root is the normative wire specification, and
// the doc comments here cite its sections. The behaviors it promises are
// pinned by an executable characterization suite, and a TypeScript port
// (ts/) implements the same wire, verified against a real Go server.
package drpc
