// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: drpc/envelope.proto

package drpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is the wire unit: every transport message/datagram is exactly one
// marshaled Envelope holding 1..n frames, processed in order. See PROTOCOL.md §4.1.
type Envelope struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Frames *[]*Frame              `protobuf:"bytes,1,rep,name=frames"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_drpc_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_drpc_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Envelope) GetFrames() []*Frame {
	if x != nil {
		if x.xxx_hidden_Frames != nil {
			return *x.xxx_hidden_Frames
		}
	}
	return nil
}

func (x *Envelope) SetFrames(v []*Frame) {
	x.xxx_hidden_Frames = &v
}

type Envelope_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Frames []*Frame
}

func (b0 Envelope_builder) Build() *Envelope {
	m0 := &Envelope{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Frames = &b.Frames
	return m0
}

var File_drpc_envelope_proto protoreflect.FileDescriptor

const file_drpc_envelope_proto_rawDesc = "" +
	"\n" +
	"\x13drpc/envelope.proto\x12\x04drpc\x1a\x10drpc/frame.proto\"/\n" +
	"\bEnvelope\x12#\n" +
	"\x06frames\x18\x01 \x03(\v2\v.drpc.FrameR\x06framesB%Z#github.com/lesomnus/grpc-dgram;drpcb\beditionsp\xe8\a"

var file_drpc_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_drpc_envelope_proto_goTypes = []any{
	(*Envelope)(nil), // 0: drpc.Envelope
	(*Frame)(nil),    // 1: drpc.Frame
}
var file_drpc_envelope_proto_depIdxs = []int32{
	1, // 0: drpc.Envelope.frames:type_name -> drpc.Frame
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_drpc_envelope_proto_init() }
func file_drpc_envelope_proto_init() {
	if File_drpc_envelope_proto != nil {
		return
	}
	file_drpc_frame_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drpc_envelope_proto_rawDesc), len(file_drpc_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_drpc_envelope_proto_goTypes,
		DependencyIndexes: file_drpc_envelope_proto_depIdxs,
		MessageInfos:      file_drpc_envelope_proto_msgTypes,
	}.Build()
	File_drpc_envelope_proto = out.File
	file_drpc_envelope_proto_goTypes = nil
	file_drpc_envelope_proto_depIdxs = nil
}
