// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: drpc/frame.proto

package drpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Frame is the unit of the drpc protocol. See PROTOCOL.md §5.
//
// Flags (bitmask on `flags`). The first five are the frame's SHAPE and are
// mutually exclusive with "no flags" (a data or header frame); COMPRESSED is
// orthogonal and may ride any payload-bearing frame.
//
//	1  = OPEN       — creates the call; client→server only; seq MUST be 1.
//	2  = CLOSE      — sender's direction finished; with `code` it is terminal.
//	4  = RESET      — stateless "no such call"; `epoch` echoes the offending frame.
//	8  = PING       — sid 0: peer keepalive; sid≠0: stream probe.
//	16 = WINDOW     — stateless flow-control credit for `sid` (reliable mode).
//	32 = COMPRESSED — `payload` is compressed with the call's compressor.
type Frame struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Epoch       uint32                 `protobuf:"fixed32,1,opt,name=epoch"`
	xxx_hidden_Sid         uint32                 `protobuf:"fixed32,2,opt,name=sid"`
	xxx_hidden_Seq         uint32                 `protobuf:"fixed32,3,opt,name=seq"`
	xxx_hidden_Flags       uint32                 `protobuf:"varint,4,opt,name=flags"`
	xxx_hidden_Method      string                 `protobuf:"bytes,5,opt,name=method"`
	xxx_hidden_Codec       string                 `protobuf:"bytes,7,opt,name=codec"`
	xxx_hidden_Timeout     *durationpb.Duration   `protobuf:"bytes,8,opt,name=timeout"`
	xxx_hidden_Payload     []byte                 `protobuf:"bytes,9,opt,name=payload"`
	xxx_hidden_Code        uint32                 `protobuf:"varint,10,opt,name=code"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,11,opt,name=desc"`
	xxx_hidden_Header      *Metadata              `protobuf:"bytes,12,opt,name=header"`
	xxx_hidden_Trailer     *Metadata              `protobuf:"bytes,13,opt,name=trailer"`
	xxx_hidden_PeerEpoch   uint32                 `protobuf:"fixed32,14,opt,name=peer_epoch,json=peerEpoch"`
	xxx_hidden_Window      uint32                 `protobuf:"varint,15,opt,name=window"`
	xxx_hidden_Compressor  string                 `protobuf:"bytes,16,opt,name=compressor"`
	xxx_hidden_Details     *[]*anypb.Any          `protobuf:"bytes,17,rep,name=details"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_drpc_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_drpc_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Frame) GetEpoch() uint32 {
	if x != nil {
		return x.xxx_hidden_Epoch
	}
	return 0
}

func (x *Frame) GetSid() uint32 {
	if x != nil {
		return x.xxx_hidden_Sid
	}
	return 0
}

func (x *Frame) GetSeq() uint32 {
	if x != nil {
		return x.xxx_hidden_Seq
	}
	return 0
}

func (x *Frame) GetFlags() uint32 {
	if x != nil {
		return x.xxx_hidden_Flags
	}
	return 0
}

func (x *Frame) GetMethod() string {
	if x != nil {
		return x.xxx_hidden_Method
	}
	return ""
}

func (x *Frame) GetCodec() string {
	if x != nil {
		return x.xxx_hidden_Codec
	}
	return ""
}

func (x *Frame) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Timeout
	}
	return nil
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *Frame) GetCode() uint32 {
	if x != nil {
		return x.xxx_hidden_Code
	}
	return 0
}

func (x *Frame) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *Frame) GetHeader() *Metadata {
	if x != nil {
		return x.xxx_hidden_Header
	}
	return nil
}

func (x *Frame) GetTrailer() *Metadata {
	if x != nil {
		return x.xxx_hidden_Trailer
	}
	return nil
}

func (x *Frame) GetPeerEpoch() uint32 {
	if x != nil {
		return x.xxx_hidden_PeerEpoch
	}
	return 0
}

func (x *Frame) GetWindow() uint32 {
	if x != nil {
		return x.xxx_hidden_Window
	}
	return 0
}

func (x *Frame) GetCompressor() string {
	if x != nil {
		return x.xxx_hidden_Compressor
	}
	return ""
}

func (x *Frame) GetDetails() []*anypb.Any {
	if x != nil {
		if x.xxx_hidden_Details != nil {
			return *x.xxx_hidden_Details
		}
	}
	return nil
}

func (x *Frame) SetEpoch(v uint32) {
	x.xxx_hidden_Epoch = v
}

func (x *Frame) SetSid(v uint32) {
	x.xxx_hidden_Sid = v
}

func (x *Frame) SetSeq(v uint32) {
	x.xxx_hidden_Seq = v
}

func (x *Frame) SetFlags(v uint32) {
	x.xxx_hidden_Flags = v
}

func (x *Frame) SetMethod(v string) {
	x.xxx_hidden_Method = v
}

func (x *Frame) SetCodec(v string) {
	x.xxx_hidden_Codec = v
}

func (x *Frame) SetTimeout(v *durationpb.Duration) {
	x.xxx_hidden_Timeout = v
}

func (x *Frame) SetPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Payload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 16)
}

func (x *Frame) SetCode(v uint32) {
	x.xxx_hidden_Code = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 16)
}

func (x *Frame) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *Frame) SetHeader(v *Metadata) {
	x.xxx_hidden_Header = v
}

func (x *Frame) SetTrailer(v *Metadata) {
	x.xxx_hidden_Trailer = v
}

func (x *Frame) SetPeerEpoch(v uint32) {
	x.xxx_hidden_PeerEpoch = v
}

func (x *Frame) SetWindow(v uint32) {
	x.xxx_hidden_Window = v
}

func (x *Frame) SetCompressor(v string) {
	x.xxx_hidden_Compressor = v
}

func (x *Frame) SetDetails(v []*anypb.Any) {
	x.xxx_hidden_Details = &v
}

func (x *Frame) HasTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timeout != nil
}

func (x *Frame) HasPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Frame) HasCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *Frame) HasHeader() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Header != nil
}

func (x *Frame) HasTrailer() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Trailer != nil
}

func (x *Frame) ClearTimeout() {
	x.xxx_hidden_Timeout = nil
}

func (x *Frame) ClearPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Payload = nil
}

func (x *Frame) ClearCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Code = 0
}

func (x *Frame) ClearHeader() {
	x.xxx_hidden_Header = nil
}

func (x *Frame) ClearTrailer() {
	x.xxx_hidden_Trailer = nil
}

type Frame_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Sender's incarnation nonce, chosen at random per Conn/Server instance.
	// Exception: RESET frames echo the epoch of the frame they answer.
	Epoch uint32
	// Stream id, client-allocated, starting at 1, never reused within an
	// epoch. 0 is reserved for peer-scope control frames (PING).
	Sid uint32
	// Per-stream, per-direction sequence, starting at 1.
	// Stateless frames (RESET, PING) carry 0.
	Seq uint32
	// Flag bitmask; see message comment.
	Flags uint32
	// Full method name (e.g. "/echo.EchoService/Once"); OPEN frames only,
	// where it MUST be present — methods are addressed by string, always.
	Method string
	// Codec name; OPEN frames only; "" means proto.
	Codec string
	// Remaining call budget at send time; OPEN frames only.
	Timeout *durationpb.Duration
	// One marshaled message. Presence is meaningful: a flag-less frame WITH
	// payload is a data frame (even when the message marshals to 0 bytes);
	// WITHOUT payload it is a header frame.
	Payload []byte
	// gRPC status code; meaningful only on CLOSE frames, where presence
	// distinguishes terminal CLOSE (code set) from half-close (unset).
	// See https://grpc.io/docs/guides/status-codes/.
	Code *uint32
	// Status description.
	Desc    string
	Header  *Metadata
	Trailer *Metadata
	// The client incarnation this frame addresses (PROTOCOL.md §6.1).
	// Server→client call frames (H, data, T, stream probes, keepalive) echo the
	// client epoch of the call they belong to; the client accepts a frame into
	// a stream only when this names its own epoch — a sid alone does not,
	// because a restarted client re-allocates sids from 1. A client→server
	// RESET echoes the offending frame's peer_epoch so the server can reset
	// exactly that incarnation's call. Client→server call frames leave it 0
	// (their field 1 already names the incarnation).
	PeerEpoch uint32
	// Flow-control credit, in messages, for this stream — reliable mode only
	// (§4.2). On OPEN and on the creation-ack H it advertises the sender's
	// initial receive window; on a WINDOW frame it is an additive grant.
	// Field 15 — the last one-byte tag — because it rides frequent frames.
	Window uint32
	// Message compressor name; OPEN frames only; "" = none. Like `codec`, it
	// governs the whole call in both directions. A frame whose payload is
	// actually compressed carries the COMPRESSED flag (§12.1).
	Compressor string
	// Rich status details — the payload of google.rpc.Status.details, i.e. what
	// status.WithDetails attaches. Terminal frames only. Best effort: a
	// terminal that would not fit the channel is re-sent without them
	// (PROTOCOL.md §4.4, §5).
	Details []*anypb.Any
}

func (b0 Frame_builder) Build() *Frame {
	m0 := &Frame{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Epoch = b.Epoch
	x.xxx_hidden_Sid = b.Sid
	x.xxx_hidden_Seq = b.Seq
	x.xxx_hidden_Flags = b.Flags
	x.xxx_hidden_Method = b.Method
	x.xxx_hidden_Codec = b.Codec
	x.xxx_hidden_Timeout = b.Timeout
	if b.Payload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 16)
		x.xxx_hidden_Payload = b.Payload
	}
	if b.Code != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 16)
		x.xxx_hidden_Code = *b.Code
	}
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Header = b.Header
	x.xxx_hidden_Trailer = b.Trailer
	x.xxx_hidden_PeerEpoch = b.PeerEpoch
	x.xxx_hidden_Window = b.Window
	x.xxx_hidden_Compressor = b.Compressor
	x.xxx_hidden_Details = &b.Details
	return m0
}

var File_drpc_frame_proto protoreflect.FileDescriptor

const file_drpc_frame_proto_rawDesc = "" +
	"\n" +
	"\x10drpc/frame.proto\x12\x04drpc\x1a\x13drpc/metadata.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\"\xf7\x03\n" +
	"\x05Frame\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\aR\x05epoch\x12\x10\n" +
	"\x03sid\x18\x02 \x01(\aR\x03sid\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\aR\x03seq\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x14\n" +
	"\x05codec\x18\a \x01(\tR\x05codec\x123\n" +
	"\atimeout\x18\b \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1f\n" +
	"\apayload\x18\t \x01(\fB\x05\xaa\x01\x02\b\x01R\apayload\x12\x19\n" +
	"\x04code\x18\n" +
	" \x01(\rB\x05\xaa\x01\x02\b\x01R\x04code\x12\x12\n" +
	"\x04desc\x18\v \x01(\tR\x04desc\x12&\n" +
	"\x06header\x18\f \x01(\v2\x0e.drpc.MetadataR\x06header\x12(\n" +
	"\atrailer\x18\r \x01(\v2\x0e.drpc.MetadataR\atrailer\x12\x1d\n" +
	"\n" +
	"peer_epoch\x18\x0e \x01(\aR\tpeerEpoch\x12\x16\n" +
	"\x06window\x18\x0f \x01(\rR\x06window\x12\x1e\n" +
	"\n" +
	"compressor\x18\x10 \x01(\tR\n" +
	"compressor\x12.\n" +
	"\adetails\x18\x11 \x03(\v2\x14.google.protobuf.AnyR\adetailsJ\x04\b\x06\x10\aR\fmethod_indexB*Z#github.com/lesomnus/grpc-dgram;drpc\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_drpc_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_drpc_frame_proto_goTypes = []any{
	(*Frame)(nil),               // 0: drpc.Frame
	(*durationpb.Duration)(nil), // 1: google.protobuf.Duration
	(*Metadata)(nil),            // 2: drpc.Metadata
	(*anypb.Any)(nil),           // 3: google.protobuf.Any
}
var file_drpc_frame_proto_depIdxs = []int32{
	1, // 0: drpc.Frame.timeout:type_name -> google.protobuf.Duration
	2, // 1: drpc.Frame.header:type_name -> drpc.Metadata
	2, // 2: drpc.Frame.trailer:type_name -> drpc.Metadata
	3, // 3: drpc.Frame.details:type_name -> google.protobuf.Any
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_drpc_frame_proto_init() }
func file_drpc_frame_proto_init() {
	if File_drpc_frame_proto != nil {
		return
	}
	file_drpc_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drpc_frame_proto_rawDesc), len(file_drpc_frame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_drpc_frame_proto_goTypes,
		DependencyIndexes: file_drpc_frame_proto_depIdxs,
		MessageInfos:      file_drpc_frame_proto_msgTypes,
	}.Build()
	File_drpc_frame_proto = out.File
	file_drpc_frame_proto_goTypes = nil
	file_drpc_frame_proto_depIdxs = nil
}
