// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: drpc/frame.proto

package drpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frame struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sid         uint32                 `protobuf:"fixed32,1,opt,name=sid"`
	xxx_hidden_Seq         uint32                 `protobuf:"fixed32,2,opt,name=seq"`
	xxx_hidden_Codec       string                 `protobuf:"bytes,3,opt,name=codec"`
	xxx_hidden_Method      string                 `protobuf:"bytes,4,opt,name=method"`
	xxx_hidden_MethodIndex uint32                 `protobuf:"varint,5,opt,name=method_index,json=methodIndex"`
	xxx_hidden_Deadline    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deadline"`
	xxx_hidden_Payload     []byte                 `protobuf:"bytes,8,opt,name=payload"`
	xxx_hidden_Code        uint32                 `protobuf:"varint,9,opt,name=code"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,10,opt,name=desc"`
	xxx_hidden_Header      *Metadata              `protobuf:"bytes,11,opt,name=header"`
	xxx_hidden_Trailer     *Metadata              `protobuf:"bytes,12,opt,name=trailer"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_drpc_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_drpc_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Frame) GetSid() uint32 {
	if x != nil {
		return x.xxx_hidden_Sid
	}
	return 0
}

func (x *Frame) GetSeq() uint32 {
	if x != nil {
		return x.xxx_hidden_Seq
	}
	return 0
}

func (x *Frame) GetCodec() string {
	if x != nil {
		return x.xxx_hidden_Codec
	}
	return ""
}

func (x *Frame) GetMethod() string {
	if x != nil {
		return x.xxx_hidden_Method
	}
	return ""
}

func (x *Frame) GetMethodIndex() uint32 {
	if x != nil {
		return x.xxx_hidden_MethodIndex
	}
	return 0
}

func (x *Frame) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Deadline
	}
	return nil
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *Frame) GetCode() uint32 {
	if x != nil {
		return x.xxx_hidden_Code
	}
	return 0
}

func (x *Frame) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *Frame) GetHeader() *Metadata {
	if x != nil {
		return x.xxx_hidden_Header
	}
	return nil
}

func (x *Frame) GetTrailer() *Metadata {
	if x != nil {
		return x.xxx_hidden_Trailer
	}
	return nil
}

func (x *Frame) SetSid(v uint32) {
	x.xxx_hidden_Sid = v
}

func (x *Frame) SetSeq(v uint32) {
	x.xxx_hidden_Seq = v
}

func (x *Frame) SetCodec(v string) {
	x.xxx_hidden_Codec = v
}

func (x *Frame) SetMethod(v string) {
	x.xxx_hidden_Method = v
}

func (x *Frame) SetMethodIndex(v uint32) {
	x.xxx_hidden_MethodIndex = v
}

func (x *Frame) SetDeadline(v *timestamppb.Timestamp) {
	x.xxx_hidden_Deadline = v
}

func (x *Frame) SetPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Payload = v
}

func (x *Frame) SetCode(v uint32) {
	x.xxx_hidden_Code = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 11)
}

func (x *Frame) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *Frame) SetHeader(v *Metadata) {
	x.xxx_hidden_Header = v
}

func (x *Frame) SetTrailer(v *Metadata) {
	x.xxx_hidden_Trailer = v
}

func (x *Frame) HasDeadline() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Deadline != nil
}

func (x *Frame) HasCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Frame) HasHeader() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Header != nil
}

func (x *Frame) HasTrailer() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Trailer != nil
}

func (x *Frame) ClearDeadline() {
	x.xxx_hidden_Deadline = nil
}

func (x *Frame) ClearCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Code = 0
}

func (x *Frame) ClearHeader() {
	x.xxx_hidden_Header = nil
}

func (x *Frame) ClearTrailer() {
	x.xxx_hidden_Trailer = nil
}

type Frame_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sid   uint32
	Seq   uint32
	Codec string
	// Method is mapped to numeric index at the server.
	// Server always respond only with `method_index` so the client can learn which
	// service is mapped to what number during communication.
	Method      string
	MethodIndex uint32
	Deadline    *timestamppb.Timestamp
	Payload     []byte
	// Status code and error description.
	// See https://grpc.io/docs/guides/status-codes/.
	Code    *uint32
	Desc    string
	Header  *Metadata
	Trailer *Metadata
}

func (b0 Frame_builder) Build() *Frame {
	m0 := &Frame{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Sid = b.Sid
	x.xxx_hidden_Seq = b.Seq
	x.xxx_hidden_Codec = b.Codec
	x.xxx_hidden_Method = b.Method
	x.xxx_hidden_MethodIndex = b.MethodIndex
	x.xxx_hidden_Deadline = b.Deadline
	x.xxx_hidden_Payload = b.Payload
	if b.Code != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 11)
		x.xxx_hidden_Code = *b.Code
	}
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Header = b.Header
	x.xxx_hidden_Trailer = b.Trailer
	return m0
}

var File_drpc_frame_proto protoreflect.FileDescriptor

const file_drpc_frame_proto_rawDesc = "" +
	"\n" +
	"\x10drpc/frame.proto\x12\x04drpc\x1a\x13drpc/metadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x02\n" +
	"\x05Frame\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\aR\x03sid\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\aR\x03seq\x12\x14\n" +
	"\x05codec\x18\x03 \x01(\tR\x05codec\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12!\n" +
	"\fmethod_index\x18\x05 \x01(\rR\vmethodIndex\x126\n" +
	"\bdeadline\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12\x19\n" +
	"\x04code\x18\t \x01(\rB\x05\xaa\x01\x02\b\x01R\x04code\x12\x12\n" +
	"\x04desc\x18\n" +
	" \x01(\tR\x04desc\x12&\n" +
	"\x06header\x18\v \x01(\v2\x0e.drpc.MetadataR\x06header\x12(\n" +
	"\atrailer\x18\f \x01(\v2\x0e.drpc.MetadataR\atrailerB*Z#github.com/lesomnus/grpc-dgram;drpc\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_drpc_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_drpc_frame_proto_goTypes = []any{
	(*Frame)(nil),                 // 0: drpc.Frame
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*Metadata)(nil),              // 2: drpc.Metadata
}
var file_drpc_frame_proto_depIdxs = []int32{
	1, // 0: drpc.Frame.deadline:type_name -> google.protobuf.Timestamp
	2, // 1: drpc.Frame.header:type_name -> drpc.Metadata
	2, // 2: drpc.Frame.trailer:type_name -> drpc.Metadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_drpc_frame_proto_init() }
func file_drpc_frame_proto_init() {
	if File_drpc_frame_proto != nil {
		return
	}
	file_drpc_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drpc_frame_proto_rawDesc), len(file_drpc_frame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_drpc_frame_proto_goTypes,
		DependencyIndexes: file_drpc_frame_proto_depIdxs,
		MessageInfos:      file_drpc_frame_proto_msgTypes,
	}.Build()
	File_drpc_frame_proto = out.File
	file_drpc_frame_proto_goTypes = nil
	file_drpc_frame_proto_depIdxs = nil
}
