// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: drpc/metadata.proto

package drpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state              protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Entries map[string]*Metadata_Entry `protobuf:"bytes,1,rep,name=entries" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_drpc_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_drpc_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Metadata) GetEntries() map[string]*Metadata_Entry {
	if x != nil {
		return x.xxx_hidden_Entries
	}
	return nil
}

func (x *Metadata) SetEntries(v map[string]*Metadata_Entry) {
	x.xxx_hidden_Entries = v
}

type Metadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries map[string]*Metadata_Entry
}

func (b0 Metadata_builder) Build() *Metadata {
	m0 := &Metadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = b.Entries
	return m0
}

type Metadata_Entry struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Values []string               `protobuf:"bytes,1,rep,name=values"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Metadata_Entry) Reset() {
	*x = Metadata_Entry{}
	mi := &file_drpc_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata_Entry) ProtoMessage() {}

func (x *Metadata_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_drpc_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Metadata_Entry) GetValues() []string {
	if x != nil {
		return x.xxx_hidden_Values
	}
	return nil
}

func (x *Metadata_Entry) SetValues(v []string) {
	x.xxx_hidden_Values = v
}

type Metadata_Entry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Values []string
}

func (b0 Metadata_Entry_builder) Build() *Metadata_Entry {
	m0 := &Metadata_Entry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Values = b.Values
	return m0
}

var File_drpc_metadata_proto protoreflect.FileDescriptor

const file_drpc_metadata_proto_rawDesc = "" +
	"\n" +
	"\x13drpc/metadata.proto\x12\x04drpc\"\xb4\x01\n" +
	"\bMetadata\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.drpc.Metadata.EntriesEntryR\aentries\x1a\x1f\n" +
	"\x05Entry\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\x1aP\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.drpc.Metadata.EntryR\x05value:\x028\x01B%Z#github.com/lesomnus/grpc-dgram;drpcb\beditionsp\xe8\a"

var file_drpc_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_drpc_metadata_proto_goTypes = []any{
	(*Metadata)(nil),       // 0: drpc.Metadata
	(*Metadata_Entry)(nil), // 1: drpc.Metadata.Entry
	nil,                    // 2: drpc.Metadata.EntriesEntry
}
var file_drpc_metadata_proto_depIdxs = []int32{
	2, // 0: drpc.Metadata.entries:type_name -> drpc.Metadata.EntriesEntry
	1, // 1: drpc.Metadata.EntriesEntry.value:type_name -> drpc.Metadata.Entry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_drpc_metadata_proto_init() }
func file_drpc_metadata_proto_init() {
	if File_drpc_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drpc_metadata_proto_rawDesc), len(file_drpc_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_drpc_metadata_proto_goTypes,
		DependencyIndexes: file_drpc_metadata_proto_depIdxs,
		MessageInfos:      file_drpc_metadata_proto_msgTypes,
	}.Build()
	File_drpc_metadata_proto = out.File
	file_drpc_metadata_proto_goTypes = nil
	file_drpc_metadata_proto_depIdxs = nil
}
