// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: drpc/metadata.proto

package drpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metadata carries gRPC header/trailer metadata. See PROTOCOL.md §11.
//
// A repeated Entry, not a map: a map's entry order is unspecified, and this
// protocol wants two things a map cannot give it — that a retransmitted frame
// is byte-identical (§10.3), and that two implementations produce the same
// bytes for the same metadata (the cross-language golden vectors). Senders
// emit entries in ascending key order; a receiver merges entries that repeat
// a key, in order, so the multimap semantics of gRPC metadata are kept.
type Metadata struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries *[]*Metadata_Entry     `protobuf:"bytes,1,rep,name=entries"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_drpc_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_drpc_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Metadata) GetEntries() []*Metadata_Entry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *Metadata) SetEntries(v []*Metadata_Entry) {
	x.xxx_hidden_Entries = &v
}

type Metadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries []*Metadata_Entry
}

func (b0 Metadata_builder) Build() *Metadata {
	m0 := &Metadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	return m0
}

type Metadata_Entry struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key         *string                `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_Values      [][]byte               `protobuf:"bytes,2,rep,name=values"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Metadata_Entry) Reset() {
	*x = Metadata_Entry{}
	mi := &file_drpc_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata_Entry) ProtoMessage() {}

func (x *Metadata_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_drpc_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Metadata_Entry) GetKey() string {
	if x != nil {
		if x.xxx_hidden_Key != nil {
			return *x.xxx_hidden_Key
		}
		return ""
	}
	return ""
}

func (x *Metadata_Entry) GetValues() [][]byte {
	if x != nil {
		return x.xxx_hidden_Values
	}
	return nil
}

func (x *Metadata_Entry) SetKey(v string) {
	x.xxx_hidden_Key = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Metadata_Entry) SetValues(v [][]byte) {
	x.xxx_hidden_Values = v
}

func (x *Metadata_Entry) HasKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Metadata_Entry) ClearKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Key = nil
}

type Metadata_Entry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key *string
	// Values are raw bytes, not text: gRPC's binary metadata ("-bin" keys)
	// carries arbitrary octets, which a proto `string` cannot hold (proto
	// enforces UTF-8 and marshaling fails). `bytes` and `string` share wire
	// type 2, so ASCII metadata encodes byte-identically either way.
	Values [][]byte
}

func (b0 Metadata_Entry_builder) Build() *Metadata_Entry {
	m0 := &Metadata_Entry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Key != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Key = b.Key
	}
	x.xxx_hidden_Values = b.Values
	return m0
}

var File_drpc_metadata_proto protoreflect.FileDescriptor

const file_drpc_metadata_proto_rawDesc = "" +
	"\n" +
	"\x13drpc/metadata.proto\x12\x04drpc\"m\n" +
	"\bMetadata\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.drpc.Metadata.EntryR\aentries\x1a1\n" +
	"\x05Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\fR\x06valuesB%Z#github.com/lesomnus/grpc-dgram;drpcb\beditionsp\xe8\a"

var file_drpc_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_drpc_metadata_proto_goTypes = []any{
	(*Metadata)(nil),       // 0: drpc.Metadata
	(*Metadata_Entry)(nil), // 1: drpc.Metadata.Entry
}
var file_drpc_metadata_proto_depIdxs = []int32{
	1, // 0: drpc.Metadata.entries:type_name -> drpc.Metadata.Entry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_drpc_metadata_proto_init() }
func file_drpc_metadata_proto_init() {
	if File_drpc_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drpc_metadata_proto_rawDesc), len(file_drpc_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_drpc_metadata_proto_goTypes,
		DependencyIndexes: file_drpc_metadata_proto_depIdxs,
		MessageInfos:      file_drpc_metadata_proto_msgTypes,
	}.Build()
	File_drpc_metadata_proto = out.File
	file_drpc_metadata_proto_goTypes = nil
	file_drpc_metadata_proto_depIdxs = nil
}
