// protobuf-es binding: derive a drpc MethodDesc straight from a protobuf-es v2
// service/method descriptor, so RPC types are NOT re-declared by hand — the
// generated `*_pb.ts` (from `protoc-gen-es`) is the single source of truth for
// the method path, the streaming kind, and the payload codec. This is the TS
// analog of the Go implementation plugging grpc-go's generated `ServiceDesc`
// straight into the core (G2).
//
// Entry: `@lesomnus/grpc-dgram/transport/protobuf-es`. `@bufbuild/protobuf` is a peer
// dependency — the core stays zero-dep; only this entry pulls it in.
//
//   import { fromService } from '@lesomnus/grpc-dgram/transport/protobuf-es'
//   import { EchoService } from './echo_pb'      // generated by protoc-gen-es
//   const Echo = fromService(EchoService)        // { once, many, count, live }
//   await conn.invoke(Echo.once, create(EchoRequestSchema, { text: 'hi' }))
//   server.register(Echo.once, (req) => create(EchoResponseSchema, { ... }))

import { fromBinary, toBinary, type DescMessage, type DescMethod, type MessageShape } from '@bufbuild/protobuf'
import type { GenService, GenServiceMethods } from '@bufbuild/protobuf/codegenv2'
import type { BidiDesc, ClientStreamingDesc, MethodDesc, PayloadCodec, ServerStreamingDesc, UnaryDesc } from '../desc'

// codecFor turns a protobuf-es message descriptor into a drpc PayloadCodec.
// The wire codec name stays '' (proto, §12) — protobuf-es marshals the same
// binary the Go proto codec does, so the two implementations interoperate.
function codecFor<Desc extends DescMessage>(schema: Desc): PayloadCodec<MessageShape<Desc>> {
  return {
    marshal: (v) => toBinary(schema, v),
    unmarshal: (b) => fromBinary(schema, b),
  }
}

// MethodLike is the structural subset the binding needs: a full DescMethod
// (name/parent present at runtime) with its input/output message schemas and
// method kind captured as generics so the derived MethodDesc keeps them.
type MethodLike<K extends DescMethod['methodKind'], I extends DescMessage, O extends DescMessage> = {
  readonly methodKind: K
  readonly input: I
  readonly output: O
  readonly name: string
  readonly parent: { readonly typeName: string }
}

// MethodDescFor maps a protobuf-es method to the precise drpc descriptor
// variant, so the streaming kind survives to Server.register's overloads
// (a unary method yields UnaryDesc, etc.).
type MethodDescFor<M> =
  M extends MethodLike<infer K, infer I, infer O>
    ? K extends 'unary'
      ? UnaryDesc<MessageShape<I>, MessageShape<O>>
      : K extends 'server_streaming'
        ? ServerStreamingDesc<MessageShape<I>, MessageShape<O>>
        : K extends 'client_streaming'
          ? ClientStreamingDesc<MessageShape<I>, MessageShape<O>>
          : BidiDesc<MessageShape<I>, MessageShape<O>>
    : never

// fromMethod builds a MethodDesc from one protobuf-es method descriptor
// (a `service.method.<name>` entry, or any DescMethod). The gRPC wire path is
// `/<service typeName>/<proto method name>` (§13) — the proto method name, not
// the camelCased localName, so a TS client and a Go server address the same
// method.
export function fromMethod<K extends DescMethod['methodKind'], I extends DescMessage, O extends DescMessage>(method: MethodLike<K, I, O>): MethodDescFor<MethodLike<K, I, O>> {
  const kind = method.methodKind
  const desc: MethodDesc<MessageShape<I>, MessageShape<O>> = {
    path: `/${method.parent.typeName}/${method.name}`,
    clientStreams: kind === 'client_streaming' || kind === 'bidi_streaming',
    serverStreams: kind === 'server_streaming' || kind === 'bidi_streaming',
    request: codecFor(method.input),
    response: codecFor(method.output),
    requestSchema: method.input,
    responseSchema: method.output,
  }
  return desc as MethodDescFor<MethodLike<K, I, O>>
}

// ServiceDescs is the map fromService returns: one descriptor per method,
// keyed by the generated localName (`echoService.method.once` → `descs.once`),
// each fully typed from the descriptor's input/output messages and kind.
export type ServiceDescs<S extends GenService<GenServiceMethods>> = {
  [K in keyof S['method']]: MethodDescFor<S['method'][K]>
}

// fromService derives every method of a generated protobuf-es service at once.
// Register and call against the returned descriptors — no hand-written paths,
// streaming flags, or codecs, and no drift from the `.proto`.
export function fromService<S extends GenService<GenServiceMethods>>(service: S): ServiceDescs<S> {
  const out: Record<string, MethodDesc<unknown, unknown>> = {}
  for (const key of Object.keys(service.method)) {
    // Runtime entries are full DescMethods (name/parent present); the
    // GenService value type narrows to input/output/methodKind, so cast.
    out[key] = fromMethod(service.method[key] as unknown as MethodLike<DescMethod['methodKind'], DescMessage, DescMessage>) as MethodDesc<unknown, unknown>
  }
  return out as ServiceDescs<S>
}
