// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wsecho.proto

package echopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_wsecho_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wsecho_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_wsecho_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Count uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// Delay between responses, in milliseconds; lets the demo hold a call open
	// while the server shuts down gracefully.
	IntervalMs    uint32 `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_wsecho_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wsecho_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_wsecho_proto_rawDescGZIP(), []int{1}
}

func (x *CountRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CountRequest) GetIntervalMs() uint32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Sequence      uint32                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_wsecho_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wsecho_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_wsecho_proto_rawDescGZIP(), []int{2}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoResponse) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_wsecho_proto protoreflect.FileDescriptor

const file_wsecho_proto_rawDesc = "" +
	"\n" +
	"\fwsecho.proto\x12\x06wsecho\"'\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"E\n" +
	"\fCountRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\rR\n" +
	"intervalMs\"D\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\rR\bsequence2{\n" +
	"\vEchoService\x123\n" +
	"\x04Echo\x12\x13.wsecho.EchoRequest\x1a\x14.wsecho.EchoResponse\"\x00\x127\n" +
	"\x05Count\x12\x14.wsecho.CountRequest\x1a\x14.wsecho.EchoResponse\"\x000\x01B?Z=github.com/lesomnus/grpc-dgram/examples/websocket-echo/echopbb\x06proto3"

var (
	file_wsecho_proto_rawDescOnce sync.Once
	file_wsecho_proto_rawDescData []byte
)

func file_wsecho_proto_rawDescGZIP() []byte {
	file_wsecho_proto_rawDescOnce.Do(func() {
		file_wsecho_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wsecho_proto_rawDesc), len(file_wsecho_proto_rawDesc)))
	})
	return file_wsecho_proto_rawDescData
}

var file_wsecho_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wsecho_proto_goTypes = []any{
	(*EchoRequest)(nil),  // 0: wsecho.EchoRequest
	(*CountRequest)(nil), // 1: wsecho.CountRequest
	(*EchoResponse)(nil), // 2: wsecho.EchoResponse
}
var file_wsecho_proto_depIdxs = []int32{
	0, // 0: wsecho.EchoService.Echo:input_type -> wsecho.EchoRequest
	1, // 1: wsecho.EchoService.Count:input_type -> wsecho.CountRequest
	2, // 2: wsecho.EchoService.Echo:output_type -> wsecho.EchoResponse
	2, // 3: wsecho.EchoService.Count:output_type -> wsecho.EchoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wsecho_proto_init() }
func file_wsecho_proto_init() {
	if File_wsecho_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wsecho_proto_rawDesc), len(file_wsecho_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wsecho_proto_goTypes,
		DependencyIndexes: file_wsecho_proto_depIdxs,
		MessageInfos:      file_wsecho_proto_msgTypes,
	}.Build()
	File_wsecho_proto = out.File
	file_wsecho_proto_goTypes = nil
	file_wsecho_proto_depIdxs = nil
}
